### ISSUE TITLE
Broken link on 'Undocumented options in the startosinstall command' post

### ISSUE THREAD

**Issue by ChefAustin** [grahampugh/grahampugh.github.io#8]
The hyperlink associated with the text "presentation at the Texas Apple Admins Virtual Meetup" on your "Undocumented options in the startosinstall command" blog post is dead.

The link goes to: https://grahamrpugh.com/2020/06/09/2020-05-05-texas-apple-admins-presentation.md

![image](https://user-images.githubusercontent.com/24925402/84237252-53ef6d00-aaf9-11ea-9dd1-6b59fbc928b1.png)

**Comment by grahampugh** [comment]
Thank you, should be fixed now!
